steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/project-2-450420/project-1', '.']
  
  # Step 2: Push the image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/project-2-450420/project-1']
  
  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'project-1'
      - '--image'
      - 'gcr.io/project-2-450420/project-1'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--add-cloudsql-instances'
      - 'project-2-450420:us-central1:arportal'
      - '--set-secrets'
      - 'FLASK_SECRET_KEY=flask-secret-key:latest,DATABASE_URL=database-url:latest,MESHY_API_KEY=meshy-api-key:latest'
      - '--set-env-vars'
      - 'BUCKET_NAME=project-2-450420-images'
      - '--service-account'
      - '686596926199-compute@developer.gserviceaccount.com'
      - '--memory'
      - '512Mi'  # Increase memory
      - '--cpu'
      - '1'      # Ensure 1 CPU
      # Uncomment and configure if Cloud SQL uses private IP
      # - '--vpc-connector'
      # - 'projects/project-2-450420/locations/us-central1/connectors/your-vpc-connector'

# Specify where to store build logs
logsBucket: 'gs://project-2-450420-images'

# Configure logging options
options:
  logging: GCS_ONLY