version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    environment:
      - SECRET_KEY=your_secure_secret_key
      - USERS_FILE=/data/users.json
    restart: unless-stopped
